//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectronicsMSDBEntities : DbContext
    {
        public ElectronicsMSDBEntities()
            : base("name=ElectronicsMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBank> tblBanks { get; set; }
        public virtual DbSet<tblBankTransaction> tblBankTransactions { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCostCenter> tblCostCenters { get; set; }
        public virtual DbSet<tblCostElement> tblCostElements { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomerWisePriceSetup> tblCustomerWisePriceSetups { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblEmail> tblEmails { get; set; }
        public virtual DbSet<tblExpense> tblExpenses { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
        public virtual DbSet<tblItemSize> tblItemSizes { get; set; }
        public virtual DbSet<tblLendBorrow> tblLendBorrows { get; set; }
        public virtual DbSet<tblLogIn> tblLogIns { get; set; }
        public virtual DbSet<tblMoneyReceived> tblMoneyReceiveds { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<tblPacking> tblPackings { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblPurchaseDTL> tblPurchaseDTLs { get; set; }
        public virtual DbSet<tblPurchaseHDR> tblPurchaseHDRs { get; set; }
        public virtual DbSet<tblRecipient> tblRecipients { get; set; }
        public virtual DbSet<tblSalesDTL> tblSalesDTLs { get; set; }
        public virtual DbSet<tblSalesHDR> tblSalesHDRs { get; set; }
        public virtual DbSet<tblSalesReturn> tblSalesReturns { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblSupplier> tblSuppliers { get; set; }
        public virtual DbSet<tblThana> tblThanas { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblVillage> tblVillages { get; set; }
        public virtual DbSet<tblWeight> tblWeights { get; set; }
    }
}
