//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerWisePriceSetup
    {
        public string CustId { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
